# Generated by Django 3.0.5 on 2020-05-05 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lmn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='posted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField()),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(max_length=2)),
                ('favoriteVenue', models.CharField(blank=True, max_length=200, null=True)),
                ('favoriteArtist', models.CharField(blank=True, max_length=200, null=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='userProfile_image/')),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
